### PR TITLE
Added null guards to make the lint tool not crash

### PR DESCRIPTION
**Pull request by mta-trackunit**
Seems to be crashing without these guards on my repo - I believe its mostly if you use ? as optional params.

### CODE REVIEW

**Comment by mta-trackunit** [comment]
It was something like this setup...
  @Field(type => [LatestSensorValue])
  public latest: [LatestSensorValue];
 
which works in prod ... but its not really right it should have been

  @Field(type => [LatestSensorValue])
  public latest: LatestSensorValue[];

**Comment by mta-trackunit** [comment]
Another one was like this:
@Field(type => Image, { nullable: true, description: "The uploaded image." })
  public image?(
    @Arg("ImageInput", { nullable: true }) imageInput: ImageInput,
    @Root() metadata: Metadata
  ): Image | undefined {
}
the fact that optional was used in the   public image? ... crash the tool instead of allow it to pass

**Comment by mta-trackunit** [comment]
I added test for the 2 cases... please let me know if there is anything I can do to get this PR through !

**Comment by borremosch** [comment]
LGTM, thanks for your contribution!

**Pull request merged**
