### PR TITLE
Upgrade to eslint 8

### PR DESCRIPTION
**Pull request by mta-trackunit**
Upgrade to eslint 8.

Also upgraded all other packages to close all security issues.

### CODE REVIEW

**Comment by mta-trackunit** [comment]
Any idea when you have time for the release of this?

**Comment by mta-trackunit** [comment]
Can I buy you a cup of coffee to get this released ? :)

**Review by borremosch — APPROVED** [review]
LGTM

**Comment by borremosch** [comment]
Branch cannot be merged due to conflicts

**Comment by mta-trackunit** [comment]
That is wierd... I says This branch has no conflicts with the base branch! 
image

**Comment by mta-trackunit** [comment]
Do you have any changes locally you could push to main - so I can resolve the conflicts?

**Comment by borremosch** [comment]
That's odd. This is what I'm seeing on my side. I'll have a look

github

**Comment by borremosch** [comment]
It was as simple as changing from rebase to merge

**Comment by borremosch** [comment]
New version has been pushed to NPM!

**Pull request merged**
